In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

FileNotFoundError: [Errno 2] No such file or directory: 'Churn_Modelling.csv'

In [3]:
dataset

NameError: name 'dataset' is not defined

In [4]:
print(X)

NameError: name 'X' is not defined

In [5]:
print(y)

NameError: name 'y' is not defined

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

NameError: name 'X' is not defined

In [ ]:
print(X)

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Now let's make the ANN!

In [12]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras'

In [11]:
# Initialising the ANN
classifier = Sequential()

2024-05-13 03:44:54.112594: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-13 03:44:54.804107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38239 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB MIG 7g.40gb, pci bus id: 0000:47:00.0, compute capability: 8.0


In [14]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
107/800 [===>..........................] - ETA: 0s - loss: 0.6733 - accuracy: 0.8065

2024-05-13 03:45:49.174947: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


800/800 [==============================] - 2s 1ms/step - loss: 0.5374 - accuracy: 0.7960
Epoch 2/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4802 - accuracy: 0.7960
Epoch 3/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4612 - accuracy: 0.7960
Epoch 4/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4434 - accuracy: 0.7960
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4297 - accuracy: 0.7960
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4210 - accuracy: 0.8046
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4164 - accuracy: 0.8240
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4135 - accuracy: 0.8288
Epoch 9/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4114 - accuracy: 0.8306
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4100 - accuracy: 0.8326
Epoch 11/2

Making predictions and evaluating the model

In [22]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

63/63 [==============================] - 0s 698us/step


In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

In [25]:
cm

array([[1540,   55],
       [ 270,  135]])

In [26]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [28]:
y_pred_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [29]:
y_pred

array([[0.18017937],
       [0.2846948 ],
       [0.16828218],
       ...,
       [0.07642157],
       [0.10283826],
       [0.09131186]], dtype=float32)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[1540   55]
 [ 270  135]]
Accuracy: 0.8375
Precision: 0.7105263157894737
Recall: 0.3333333333333333
F1 Score: 0.453781512605042
